# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0bInfoRequest\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x32[\n\x17RequestsReceiverService\x12@\n\x0fSendRequestInfo\x12\x13.protos.InfoRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_INFOREQUEST = _descriptor.Descriptor(
  name='InfoRequest',
  full_name='protos.InfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='protos.InfoRequest.agent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protos.InfoRequest.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['InfoRequest'] = _INFOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InfoRequest = _reflection.GeneratedProtocolMessageType('InfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFOREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:protos.InfoRequest)
  })
_sym_db.RegisterMessage(InfoRequest)



_REQUESTSRECEIVERSERVICE = _descriptor.ServiceDescriptor(
  name='RequestsReceiverService',
  full_name='protos.RequestsReceiverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=102,
  serialized_end=193,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendRequestInfo',
    full_name='protos.RequestsReceiverService.SendRequestInfo',
    index=0,
    containing_service=None,
    input_type=_INFOREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUESTSRECEIVERSERVICE)

DESCRIPTOR.services_by_name['RequestsReceiverService'] = _REQUESTSRECEIVERSERVICE

# @@protoc_insertion_point(module_scope)
