# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import server_pb2 as server__pb2


class RequestsReceiverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequestInfo = channel.unary_unary(
                '/protos.RequestsReceiverService/SendRequestInfo',
                request_serializer=server__pb2.InfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class RequestsReceiverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRequestInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequestsReceiverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRequestInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRequestInfo,
                    request_deserializer=server__pb2.InfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.RequestsReceiverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RequestsReceiverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRequestInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.RequestsReceiverService/SendRequestInfo',
            server__pb2.InfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
